// VOICE_RECOGNITION
export const VOICE_RECOGNITION = "VOICE_RECOGNITION";
export const VOICE_RECOGNITION_SUCCESS = "VOICE_RECOGNITION_SUCCESS";
export const VOICE_RECOGNITION_FAILURE = "VOICE_RECOGNITION_FAILURE";
