// Kakao AUTHORIZE
export const KAKAO_AUTHORIZE = "KAKAO_AUTHORIZE";
export const KAKAO_AUTHORIZE_SUCCESS = "KAKAO_AUTHORIZE_SUCCESS";
export const KAKAO_AUTHORIZE_FAILURE = "KAKAO_AUTHORIZE_FAILURE";
