// Paraphrase
export const PARAPHRASE_CHECK = "PARAPHRASE_CHECK";
export const PARAPHRASE_CHECK_SUCCESS = "PARAPHRASE_CHECK_SUCCESS";
export const PARAPHRASE_CHECK_FAILURE = "PARAPHRASE_CHECK_FAILURE";
