export const GET_QUIZ_REQUEST = "GET_QUIZ_REQUEST";
export const GET_QUIZ_REQUEST_SUCCESS = "GET_QUIZ_REQUEST_SUCCESS";
export const GET_QUIZ_REQUEST_FAILURE = "GET_QUIZ_REQUEST_FAILURE";
export const POST_QUIZ_RESULT = "POST_QUIZ_RESULT";
export const POST_QUIZ_RESULT_SUCCESS = "POST_QUIZ_RESULT_SUCCESS";
export const POST_QUIZ_RESULT_FAILURE = "POST_QUIZ_RESULT_FAILURE";