// SEARCHWord
export const SEARCH_WORDS_REQUEST = "SEARCH_WORDS_REQUEST";
export const SEARCH_WORDS_REQUEST_SUCCESS = "SEARCH_WORDS_REQUEST_SUCCESS";
export const SEARCH_WORDS_REQUEST_FAILURE = "SEARCH_WORDS_REQUEST_FAILURE";
export const DICTIONARY_WORDS_REQUEST = "DICTIONARY_WORDS_REQUEST";
export const DICTIONARY_WORDS_REQUEST_SUCCESS = "DICTIONARY_WORDS_REQUEST_SUCCESS";
export const DICTIONARY_WORDS_REQUEST_FAILURE = "DICTIONARY_WORDS_REQUEST_FAILURE";
