export const WORD_RANKING = "WORD_RANKING";
export const WORD_RANKING_SUCCESS = "WORD_RANKING_SUCCESS";
export const WORD_RANKING_FAILURE = "WORD_RANKING_FAILURE";
export const USER_RANKING = "USER_RANKING";
export const USER_RANKING_SUCCESS = "USER_RANKING_SUCCESS";
export const USER_RANKING_FAILURE = "USER_RANKING_FAILURE";
