// DailyWord
export const DAILY_WORDS_REQUEST = "DAILY_WORDS_REQUEST";
export const DAILY_WORDS_REQUEST_SUCCESS = "DAILY_WORDS_REQUEST_SUCCESS";
export const DAILY_WORDS_REQUEST_FAILURE = "DAILY_WORDS_REQUEST_FAILURE";
